### ISSUE TITLE
Cant dockerize cell

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#1079]
When trying to dockerize a cell we get:
```
[E 2024-01-18 12:29:13.715 ServerApp] Uncaught exception POST /vre/containerizer/extract?1705577353641 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/vre/containerizer/extract?1705577353641', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "anaconda3/envs/jupyterlab/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "anaconda3/envs/jupyterlab/lib/python3.11/site-packages/jupyterlab_vre/component_containerizer/handlers.py", line 111, in post
        extractor = HeaderExtractor(notebook, source)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "anaconda3/envs/jupyterlab/lib/python3.11/site-packages/jupyterlab_vre/services/extractor/headerextractor.py", line 51, in __init__
        self.schema = self._load_schema()
                      ^^^^^^^^^^^^^^^^^^^
      File "anaconda3/envs/jupyterlab/lib/python3.11/site-packages/jupyterlab_vre/services/extractor/headerextractor.py", line 62, in _load_schema
        with open(filename) as f:
             ^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'anaconda3/envs/jupyterlab/lib/python3.11/site-packages/jupyterlab_vre/services/extractor/cell_header.schema.json'
[W 2024-01-18 12:29:13.716 ServerApp] Unhandled error
[E 2024-01-18 12:29:13.717 ServerApp] {
      "Host": "127.0.0.1:8888",
      "Accept": "*/*",
      "Referer": "http://127.0.0.1:8888/lab/tree/Laserfarm-local.ipynb",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
    }
[E 2024-01-18 12:29:13.717 ServerApp] 500 POST /vre/containerizer/extract?1705577353641 (unknown@127.0.0.1) 23.78ms referer=http://127.0.0.1:8888/lab/tree/Laserfarm-local.ipynb
```

**Comment by skoulouzis** [comment]
It seems we are missing : cell_header.schema.json
