### ISSUE TITLE
Recursive `conf_` dependency resolution fails

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE#1332]
When a `conf_` assignment refers to another `conf_`, the dependency gets resolved by [`PyExtractor.__resolve_configurations`](https://github.com/QCDIS/NaaVRE/blob/8f1fa4f3168cc64e3c415546ef8a16ef440dbb27/jupyterlab_vre/services/extractor/pyextractor.py#L251).

However, if there is a third level of dependency, the resolution breaks. Example:

```python
# Cell A
conf_a = "a"
conf_b = conf_a + "b"
conf_c = conf_b + "c"
# Cell B
conf_c
```

fails with 

```
Uncaught exception POST /vre/containerizer/extract?1712131157437 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/vre/containerizer/extract?1712131157437', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/user/.conda/envs/jupyterlab/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/user/lwe/naavre/code/NaaVRE/jupyterlab_vre/component_containerizer/handlers.py", line 153, in post
        code_extractor = PyExtractor(notebook, source)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/lwe/naavre/code/NaaVRE/jupyterlab_vre/services/extractor/pyextractor.py", line 39, in __init__
        super().__init__(notebook, cell_source)
      File "/home/user/lwe/naavre/code/NaaVRE/jupyterlab_vre/services/extractor/extractor.py", line 19, in __init__
        self.dependencies = self.infer_cell_dependencies(self.confs)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/lwe/naavre/code/NaaVRE/jupyterlab_vre/services/extractor/pyextractor.py", line 130, in infer_cell_dependencies
        names.update(self.__extract_cell_names(confs[ck]))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/lwe/naavre/code/NaaVRE/jupyterlab_vre/services/extractor/pyextractor.py", line 194, in __extract_cell_names
        tree = ast.parse(cell_source)
               ^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/.conda/envs/jupyterlab/lib/python3.11/ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<unknown>", line 1
        conf_b + "c" = conf_b + "c"
    IndentationError: unexpected indent
```

**Comment by skoulouzis** [comment]
Using the test file test_types.json `__resolve_configurations`  never returns. 
It seems that if a variable contains 'conf' the loop doesn't return 
```python
conf_list_str = ["conf_list_str", "space in elem", "3"]
```
Assignment becomes:
```
' [" ["conf_list_str", "space in elem", "3"]", "space in elem", "3"] = [" [" ["conf_list_str", "space in elem", "3"]", "space in elem", "3"]", "space in elem", "3"]'
```

**Comment by gpelouze** [comment]
Separate issue #1364
