### ISSUE TITLE
    AttributeError: 'Attribute' object has no attribute 'id'

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#317]
```python 
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/component_containerizer/handlers.py", line 52, in post
        extractor = Extractor(notebook)
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/services/extractor/extractor.py", line 18, in __init__
        self.configurations = self.__extract_configurations(self.sources)
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/services/extractor/extractor.py", line 47, in __extract_configurations
        name = node.targets[0].id
    AttributeError: 'Attribute' object has no attribute 'id'
```

**Comment by skoulouzis** [comment]
fixed by checking if node.targets[0] has attribute id
