### ISSUE TITLE
github.GithubException.UnknownObjectException: 404

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#322]
```python 
    HTTPServerRequest(protocol='https', host='', method='POST', uri='/n-a-a-vre/user//vre/containerizer/addcell?1665662212925', version='HTTP/1.1', remote_ip='10.32.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/component_containerizer/handlers.py", line 243, in post
        update_cell_in_repository(current_cell, repository, files_info)
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/component_containerizer/handlers.py", line 280, in update_cell_in_repository
        remote_content = repository.get_contents(
      File "/opt/conda/lib/python3.9/site-packages/github/Repository.py", line 1789, in get_contents
        headers, data = self._requester.requestJsonAndCheck(
      File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
        return self.__check(
      File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
        raise self.__createException(status, responseHeaders, output)
    github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"}
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/component_containerizer/handlers.py", line 245, in post
        create_cell_in_repository(current_cell, repository, files_info)
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/component_containerizer/handlers.py", line 269, in create_cell_in_repository
        repository.create_file(
      File "/opt/conda/lib/python3.9/site-packages/github/Repository.py", line 2090, in create_file
        headers, data = self._requester.requestJsonAndCheck(
      File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
        return self.__check(
      File "/opt/conda/lib/python3.9/site-packages/github/Requester.py", line 378, in __check
        raise self.__createException(status, responseHeaders, output)
    github.GithubException.GithubException: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/reference/repos#create-or-update-file-contents"}
[W 2022-10-13 11:56:54.937 SingleUserNotebookApp handlers:612] Unhandled error
```

**Comment by skoulouzis** [comment]
Duplicated with #323
