### ISSUE TITLE
Workflow request execution fails 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#331]
```python
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/vre/expmanager/execute?1666875326076', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_vre/experiment_manager/handlers.py", line 164, in post
        self.write(resp.json())
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
[W 2022-10-27 14:55:27.471 ServerApp] Unhandled error
[E 2022-10-27 14:55:27.471 ServerApp] {
      "Host": "localhost:8888",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0"
    }
```

**Comment by skoulouzis** [comment]
We may need to add a better exception handling and message reporting to the user
