### ISSUE TITLE
Component containerizer is not creating # Fetch Laz Files.sp cell

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#36]
**Describe the bug**
Component containerizer is not showing the component on the left panel. The log shows:

    HTTPServerRequest(protocol='https', host='', method='POST', uri='/n-a-a-vre/user//vre/extractor?1641287046158', version='HTTP/1.1', remote_ip='10.32.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/handlers.py", line 75, in post
        params = list(extractor.extract_cell_params(cell.original_source))
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/extractor/extractor.py", line 118, in extract_cell_params
        cell_unds = self.__extract_cell_undefined(cell_source)
      File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/extractor/extractor.py", line 104, in __extract_cell_undefined
        raise RuntimeError("Flakes reported the following error:"
    RuntimeError: Flakes reported the following error:
    	temp:5:11: invalid syntax
    	laz_files = [f for f in list_remote(get_wdclient(conf_wd_opts), conf_remote_path_ahn.as_posix())	
    	          ^
    
[W 2022-01-04 09:04:06.617 SingleUserNotebookApp handlers:617] Unhandled error
[E 2022-01-04 09:04:06.618 SingleUserNotebookApp log:181] {
      "Cookie": "jupyterhub-user-skoulouzis=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
      "Cache-Control": "no-cache",
      "Pragma": "no-cache",
      "Sec-Gpc": "1",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Dnt": "1",
      "Origin": "https://lifewatch.lab.uvalight.net:32443",
      "X-Xsrftoken": "2|93fbc237|7bc841d4ef2a39d1de9bdf12b7528d4d|1640346236",
      "Authorization": "token [secret]",
      "Content-Type": "text/plain;charset=UTF-8",
      "Referer": "https://lifewatch.lab.uvalight.net:32443/n-a-a-vre/user/skoulouzis/lab?",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0",
      "Content-Length": "14484",
      "X-Scheme": "https",
      "X-Forwarded-Port": "443,32443",
      "X-Forwarded-Host": "lifewatch.lab.uvalight.net:32443",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-For": "10.32.0.1,::ffff:10.36.0.7",
      "X-Real-Ip": "10.32.0.1",
      "X-Request-Id": "f7cb00537c96a2bbd6f09575b1b38033",
      "Host": "lifewatch.lab.uvalight.net:32443",
      "Connection": "close"
    }

**To Reproduce**
1. Open the Demo_Notebook 
2. Click on # Fetch Laz Files.sp cell 

**Expected behavior**
Show the cell in the panel and be able to add it to the catalog 

**Screenshots**

![Screenshot from 2022-01-04 10-11-24](https://user-images.githubusercontent.com/9680609/148035900-c25b3ce3-f3b7-4299-8e95-22f206c342cd.png)

**Additional context**

**Comment by skoulouzis** [comment]
Conatiner in jupuyterhub  runs pyflakes==2.4.0 
```bash
jovyan@jupyter-skoulouzis:~$ pip freeze | grep pyflakes
pyflakes==2.4.0
```

**Comment by skoulouzis** [comment]
Not able to reproduce. Not seen for some time.
