### ISSUE TITLE
Building the docker image failes 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#38]
**Describe the bug**
```shell 
$ cd docker && docker build .
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @jupyter_vre/faicells-panel > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning @jupyter_vre/faicells-panel > @material-ui/core@4.12.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
warning @jupyter_vre/faicells-composer > @material-ui/core@4.12.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
warning @jupyter_vre/faicells-composer > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning @jupyter_vre/components > @material-ui/core@4.12.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
warning @jupyter_vre/components > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning @jupyter_vre/infrastructure-automator > @material-ui/core@4.12.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
warning @jupyter_vre/infrastructure-automator > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning @jupyter_vre/chart-customs > @material-ui/core@4.12.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
warning @jupyter_vre/chart-customs > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning @jupyter_vre/core > @material-ui/core@4.12.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
warning @jupyter_vre/core > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
warning @jupyter_vre/vre-menu > @material-ui/core@4.12.3: You can now upgrade to @mui/material. See the guide: https://mui.com/guides/migration-v4/
warning @jupyter_vre/vre-menu > crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
[3/5] Fetching packages...
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
warning @blueprintjs/core@3.52.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
error @npmcli/fs@1.1.0: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "14.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 176, in start
    raise e

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labapp.py", line 172, in start
    build(name=self.name, version=self.version,

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

[LabBuildApp]   File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 686, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occurred.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-zf4f47oc.log
The command '/bin/bash -o pipefail -c python3 -m pip install --quiet --no-cache-dir /home/jovyan/jupyterlab_vre-0.1.0-py3-none-any.whl &&     jupyter serverextension enable --py jupyterlab_vre --user &&     jupyter lab build --debug;' returned a non-zero code: 1
```

**Comment by skoulouzis** [comment]
Changed docker file and restructured actions. We can now build and push docker images
