### ISSUE TITLE
Lifewatch FailedPostStartHook 

### ISSUE THREAD

**Issue by JustinMingo** [QCDIS/NaaVRE#388]
FailedPostStartHook error

2022-12-19T14:50:12Z [Warning] Exec lifecycle hook ([sh -c mkdir -p /home/jovyan/NaaVRE && cp -r /tmp/repo_utils/conf_vl_repos.py /home/jovyan/NaaVRE/ && python /home/jovyan/NaaVRE/conf_vl_repos.py --force=True --github_url=https://github.com/QCDIS/NaaVRE-n-a-a-vre-dev-VL --github_token= --registry_url=https://hub.docker.com/u/qcdis && gitpuller https://github.com/QCDIS/lifewatch-notebooks main example_notebooks]) for Container "notebook" in Pod "jupyter-justinmingo_n-a-a-vre(4c1fab11-fe00-477f-9181-c4dbe06bb8fa)" failed - error: command 'sh -c mkdir -p /home/jovyan/NaaVRE && cp -r /tmp/repo_utils/conf_vl_repos.py /home/jovyan/NaaVRE/ && python /home/jovyan/NaaVRE/conf_vl_repos.py --force=True --github_url=https://github.com/QCDIS/NaaVRE-n-a-a-vre-dev-VL --github_token= --registry_url=https://hub.docker.com/u/qcdis && gitpuller https://github.com/QCDIS/lifewatch-notebooks main example_notebooks' exited with 1: Traceback (most recent call last): File "/opt/conda/bin/gitpuller", line 8, in <module> sys.exit(main()) File "/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py", line 310, in main for line in GitPuller( File "/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py", line 146, in pull yield from self.update() File "/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py", line 254, in update yield from self.update_remotes() File "/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py", line 192, in update_remotes yield from execute_cmd(['git', 'fetch'], cwd=self.repo_dir) File "/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py", line 45, in execute_cmd raise subprocess.CalledProcessError(ret, cmd) subprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128. , message: "$ git fetch\n\nfatal: not a git repository (or any parent up to mount point /home)\n\nStopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).\n\nTraceback (most recent call last):\n File \"/opt/conda/bin/gitpuller\", line 8, in <module>\n sys.exit(main())\n File \"/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py\", line 310, in main\n for line in GitPuller(\n File \"/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py\", line 146, in pull\n yield from self.update()\n File \"/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py\", line 254, in update\n yield from self.update_remotes()\n File \"/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py\", line 192, in update_remotes\n yield from execute_cmd(['git', 'fetch'], cwd=self.repo_dir)\n File \"/opt/conda/lib/python3.9/site-packages/nbgitpuller/pull.py\", line 45, in execute_cmd\n raise subprocess.CalledProcessError(ret, cmd)\nsubprocess.CalledProcessError: Command '['git', 'fetch']' returned non-zero exit status 128.\n"

**Comment by skoulouzis** [comment]
Can't reproduce
