### ISSUE TITLE
No such file or directory: 'g++' in cell containerization

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#392]
```python 
     [Errno 2] No such file or directory: 'g++'
      
      
      Traceback (most recent call last):
        File "/opt/conda/envs/venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/opt/conda/envs/venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/conda/envs/venv/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 493, in <module>
          setup_package()
        File "setup.py", line 485, in setup_package
          setup(**metadata)
        File "/tmp/pip-install-tfnuncg_/numpy_1262577725f54ec19892aeddbc4c54c9/numpy/distutils/core.py", line 169, in setup
          return old_setup(**new_attr)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-tfnuncg_/numpy_1262577725f54ec19892aeddbc4c54c9/numpy/distutils/command/build.py", line 62, in run
          old_build.run(self)
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-azsdds5i/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-tfnuncg_/numpy_1262577725f54ec19892aeddbc4c54c9/numpy/distutils/command/build_src.py", line 144, in run
          self.build_sources()
        File "/tmp/pip-install-tfnuncg_/numpy_1262577725f54ec19892aeddbc4c54c9/numpy/distutils/command/build_src.py", line 155, in build_sources
          self.build_library_sources(*libname_info)
        File "/tmp/pip-install-tfnuncg_/numpy_1262577725f54ec19892aeddbc4c54c9/numpy/distutils/command/build_src.py", line 288, in build_library_sources
          sources = self.generate_sources(sources, (lib_name, build_info))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-tfnuncg_/numpy_1262577725f54ec19892aeddbc4c54c9/numpy/distutils/command/build_src.py", line 378, in generate_sources
          source = func(extension, build_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-tfnuncg_/numpy_1262577725f54ec19892aeddbc4c54c9/numpy/core/setup.py", line 757, in get_mathlib_info
          raise RuntimeError(
      RuntimeError: Broken toolchain: cannot link a simple C++ program. note: A compiler with support for C++11 language features is required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for numpy
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```

**Comment by skoulouzis** [comment]
Looks like we are missing g++
