### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 5 (char 4)

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#406]
```python 
Traceback (most recent call last):
  File "//retiling-dev-skoulouzis.py", line 23, in <module>
    split_laz_files = json.loads(args.split_laz_files.replace('\'','').replace('[','["').replace(']','"]'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 5 (char 4)
```

**Comment by skoulouzis** [comment]
We probably need to add a merger to the WF

**Comment by skoulouzis** [comment]
We solve it by adding one more cell to fetch the list of files
