### ISSUE TITLE
In notebook search when we send the rating we get an error

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#488]
In notebook search when we send the rating we get an error
```
    Traceback (most recent call last):
      File "/venv/lib/python3.11/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/venv/lib/python3.11/site-packages/jupyterlab_vre/notebook_search/handlers.py", line 119, in post
        'num_stars': str(notebook['rating']),
```

**Comment by skoulouzis** [comment]
Timeout
