### ISSUE TITLE
Build and start the NaaVRE on the dev env

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#584]
Executed commands:
```
conda create -n jupyterlab  python=3.9 
conda activate jupyterlab
conda env update -f environment.yml
conda install jupyterlab nodejs yarn
conda install -c conda-forge typescript 
npm install lerna --force
npm install --force
make install-backend && make build-frontend && make install-ui && make link-ui
```

Succesful so far. Running `jupyter lab build && jupyter lab --debug --watch` gives:
```
[LabBuildApp] WARNING | Config option `kernel_spec_manager_class` not recognized by `LabBuildApp`.
[LabBuildApp] JupyterLab 3.6.1
[LabBuildApp] Building in /usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (development)
Build failed.
Troubleshooting: If the build failed due to an out-of-memory error, you
may be able to fix it by disabling the `dev_build` and/or `minimize` options.

If you are building via the `jupyter lab build` command, you can disable
these options like so:

jupyter lab build --dev-build=False --minimize=False

You can also disable these options for all JupyterLab builds by adding these
lines to a Jupyter config file named `jupyter_config.py`:

c.LabBuildApp.minimize = False
c.LabBuildApp.dev_build = False

If you don't already have a `jupyter_config.py` file, you can create one by
adding a blank file of that name to any of the Jupyter config directories.
The config directories can be listed by running:

jupyter --paths

Explanation:

- `dev-build`: This option controls whether a `dev` or a more streamlined
`production` build is used. This option will default to `False` (i.e., the
`production` build) for most users. However, if you have any labextensions
installed from local files, this option will instead default to `True`.
Explicitly setting `dev-build` to `False` will ensure that the `production`
build is used in all circumstances.

- `minimize`: This option controls whether your JS bundle is minified
during the Webpack build, which helps to improve JupyterLab's overall
performance. However, the minifier plugin used by Webpack is very memory
intensive, so turning it off may help the build finish successfully in
low-memory environments.

An error occurred.
RuntimeError: JupyterLab failed to build
See the log file for details:  /var/folders/7n/q7mx8hx94bqdmbd91vplkyx40000gn/T/jupyterlab-debug-guejpcor.log

```

**Comment by skoulouzis** [comment]
@DiederikBlanson  Could you post the contents of '/var/folders/7n/q7mx8hx94bqdmbd91vplkyx40000gn/T/jupyterlab-debug-guejpcor.log'

**Comment by DiederikBlanson** [comment]
@skoulouzis The issue seems related to this https://stackoverflow.com/questions/64413433/webpack-serve-giving-invalid-regular-expression-error


```
 [LabBuildApp] Building in /usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab
[LabBuildApp] Node v18.15.0

[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Building jupyterlab assets (development)
[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/notebook-search
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/notebook-search@1.0.0
npm notice === Tarball Contents === 
npm notice 245B   lib/NotebookDownload.d.ts           
npm notice 4.2kB  lib/NotebookDownload.js             
npm notice 248B   lib/NotebookDownloadDialogue.d.ts   
npm notice 5.2kB  lib/NotebookDownloadDialogue.js     
npm notice 244B   lib/NotebookScrollDialog.d.ts       
npm notice 8.2kB  lib/NotebookScrollDialog.js         
npm notice 811B   lib/NotebookSearchPanel.d.ts        
npm notice 9.5kB  lib/NotebookSearchPanel.js          
npm notice 249B   lib/NotebookSearchWidget.d.ts       
npm notice 2.9kB  lib/NotebookSearchWidget.js         
npm notice 246B   lib/NotebookSendRating.d.ts         
npm notice 4.3kB  lib/NotebookSendRating.js           
npm notice 259B   lib/NotebookVirtualizedList.d.ts    
npm notice 3.0kB  lib/NotebookVirtualizedList.js      
npm notice 63B    lib/Theme.d.ts                      
npm notice 452B   lib/Theme.js                        
npm notice 144B   lib/index.d.ts                      
npm notice 351B   lib/index.js                        
npm notice 1.3kB  package.json                        
npm notice 2.0kB  src/NotebookDownload.tsx            
npm notice 2.9kB  src/NotebookDownloadDialogue.tsx    
npm notice 5.1kB  src/NotebookScrollDialog.tsx        
npm notice 6.3kB  src/NotebookSearchPanel.tsx         
npm notice 1.2kB  src/NotebookSearchWidget.tsx        
npm notice 2.1kB  src/NotebookSendRating.tsx          
npm notice 1.7kB  src/NotebookVirtualizedList.tsx     
npm notice 293B   src/Theme.ts                        
npm notice 195B   src/index.ts                        
npm notice 79B    src/svg.d.ts                        
npm notice 628B   style/icons/notebook_search_icon.svg
npm notice 10.8kB style/index.css                     
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/notebook-search            
npm notice version:       1.0.0                                   
npm notice filename:      jupyter_vre-notebook-search-1.0.0.tgz   
npm notice package size:  16.1 kB                                 
npm notice unpacked size: 75.2 kB                                 
npm notice shasum:        31773b05eb9c7715fa59d003aeb6c4d3c42eed23
npm notice integrity:     sha512-qINdzI84gCRLl[...]gVQ6ogypMB3vg==
npm notice total files:   31                                      
npm notice 
jupyter_vre-notebook-search-1.0.0.tgz

[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/core
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/core@1.0.0
npm notice === Tarball Contents === 
npm notice 231B  lib/CellPreview.d.ts
npm notice 2.3kB lib/CellPreview.js  
npm notice 190B  lib/index.d.ts      
npm notice 463B  lib/index.js        
npm notice 279B  lib/requests.d.ts   
npm notice 2.1kB lib/requests.js     
npm notice 503B  lib/types.d.ts      
npm notice 77B   lib/types.js        
npm notice 1.3kB package.json        
npm notice 1.3kB src/CellPreview.tsx 
npm notice 205B  src/index.ts        
npm notice 24B   src/lodash.d.ts     
npm notice 1.1kB src/requests.ts     
npm notice 657B  src/types.ts        
npm notice 10B   style/index.css     
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/core                       
npm notice version:       1.0.0                                   
npm notice filename:      jupyter_vre-core-1.0.0.tgz              
npm notice package size:  3.4 kB                                  
npm notice unpacked size: 10.7 kB                                 
npm notice shasum:        ed0f4d4e4b4fca7a417189ce90b5ca17c297c979
npm notice integrity:     sha512-11Sb6v92QrVWB[...]YmJDBU3qIKThA==
npm notice total files:   15                                      
npm notice 
jupyter_vre-core-1.0.0.tgz

[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/notebook-containerizer
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/notebook-containerizer@1.0.0
npm notice === Tarball Contents === 
npm notice 602B  lib/NotebookContainerizerDialog.d.ts
npm notice 3.3kB lib/NotebookContainerizerDialog.js  
npm notice 63B   lib/Theme.d.ts                      
npm notice 452B  lib/Theme.js                        
npm notice 745B  lib/index.d.ts                      
npm notice 2.9kB lib/index.js                        
npm notice 1.2kB package.json                        
npm notice 1.6kB src/NotebookContainerizerDialog.tsx 
npm notice 293B  src/Theme.ts                        
npm notice 2.3kB src/index.tsx                       
npm notice 10B   style/index.css                     
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/notebook-containerizer         
npm notice version:       1.0.0                                       
npm notice filename:      jupyter_vre-notebook-containerizer-1.0.0.tgz
npm notice package size:  3.5 kB                                      
npm notice unpacked size: 13.5 kB                                     
npm notice shasum:        750e6c4e4f768242b78de3fcec7b3b16157f155a    
npm notice integrity:     sha512-cgWpno9EF/I4Q[...]+fRHEYvQvAT5Q==    
npm notice total files:   11                                          
npm notice 
jupyter_vre-notebook-containerizer-1.0.0.tgz

[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/chart-customs
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/chart-customs@1.0.0
npm notice === Tarball Contents === 
npm notice 360B  lib/NodeCustom.d.ts       
npm notice 4.0kB lib/NodeCustom.js         
npm notice 166B  lib/NodeInnerCustom.d.ts  
npm notice 2.5kB lib/NodeInnerCustom.js    
npm notice 140B  lib/PortCustom.d.ts       
npm notice 3.3kB lib/PortCustom.js         
npm notice 191B  lib/index.d.ts            
npm notice 682B  lib/index.js              
npm notice 1.2kB package.json              
npm notice 2.3kB src/NodeCustom.tsx        
npm notice 1.2kB src/NodeInnerCustom.tsx   
npm notice 1.8kB src/PortCustom.tsx        
npm notice 202B  src/index.ts              
npm notice 35B   src/styled-components.d.ts
npm notice 0B    style/index.css           
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/chart-customs              
npm notice version:       1.0.0                                   
npm notice filename:      jupyter_vre-chart-customs-1.0.0.tgz     
npm notice package size:  3.8 kB                                  
npm notice unpacked size: 18.1 kB                                 
npm notice shasum:        b2d7846988ede2273fb576ef7d3d8937cd5dce78
npm notice integrity:     sha512-NFywP24t1ntY9[...]Dw8H4fyhbN81w==
npm notice total files:   15                                      
npm notice 
jupyter_vre-chart-customs-1.0.0.tgz

[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/components
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/components@1.0.0
npm notice === Tarball Contents === 
npm notice 282B  lib/CellEditor.d.ts       
npm notice 1.8kB lib/CellEditor.js         
npm notice 293B  lib/CellInfo.d.ts         
npm notice 3.8kB lib/CellInfo.js           
npm notice 114B  lib/Page.d.ts             
npm notice 1.6kB lib/Page.js               
npm notice 235B  lib/VirtualizedList.d.ts  
npm notice 2.4kB lib/VirtualizedList.js    
npm notice 222B  lib/index.d.ts            
npm notice 823B  lib/index.js              
npm notice 1.2kB package.json              
npm notice 735B  src/CellEditor.tsx        
npm notice 4.2kB src/CellInfo.tsx          
npm notice 597B  src/Page.tsx              
npm notice 1.3kB src/VirtualizedList.tsx   
npm notice 237B  src/index.ts              
npm notice 35B   src/styled-components.d.ts
npm notice 10B   style/index.css           
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/components                 
npm notice version:       1.0.0                                   
npm notice filename:      jupyter_vre-components-1.0.0.tgz        
npm notice package size:  4.1 kB                                  
npm notice unpacked size: 19.8 kB                                 
npm notice shasum:        696fc9bde61388fa642ae66d1b5ebd58d61005e5
npm notice integrity:     sha512-JX04aNhIJ0F52[...]cNCcQCkFaUdsg==
npm notice total files:   18                                      
npm notice 
jupyter_vre-components-1.0.0.tgz

[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/experiment-manager
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/experiment-manager@1.0.0
npm notice === Tarball Contents === 
npm notice 863B   lib/CatalogDialog.d.ts           
npm notice 5.2kB  lib/CatalogDialog.js             
npm notice 1.3kB  lib/Composer.d.ts                
npm notice 7.7kB  lib/Composer.js                  
npm notice 874B   lib/ExecuteWorkflowDialog.d.ts   
npm notice 7.4kB  lib/ExecuteWorkflowDialog.js     
npm notice 124B   lib/Parallelization.d.ts         
npm notice 3.8kB  lib/Parallelization.js           
npm notice 264B   lib/SidebarSpecialItem.d.ts      
npm notice 2.0kB  lib/SidebarSpecialItem.js        
npm notice 230B   lib/SpeedDial.d.ts               
npm notice 3.0kB  lib/SpeedDial.js                 
npm notice 70B    lib/Theme.d.ts                   
npm notice 463B   lib/Theme.js                     
npm notice 540B   lib/Workspace.d.ts               
npm notice 3.6kB  lib/Workspace.js                 
npm notice 353B   lib/WorkspaceItem.d.ts           
npm notice 2.9kB  lib/WorkspaceItem.js             
npm notice 95B    lib/emptyChart.d.ts              
npm notice 262B   lib/emptyChart.js                
npm notice 145B   lib/index.d.ts                   
npm notice 14.3kB lib/index.js                     
npm notice 2.1kB  package.json                     
npm notice 3.9kB  src/CatalogDialog.tsx            
npm notice 4.5kB  src/Composer.tsx                 
npm notice 6.3kB  src/ExecuteWorkflowDialog.tsx    
npm notice 2.8kB  src/Parallelization.tsx          
npm notice 746B   src/SidebarSpecialItem.tsx       
npm notice 1.9kB  src/SpeedDial.tsx                
npm notice 300B   src/Theme.ts                     
npm notice 2.5kB  src/Workspace.tsx                
npm notice 1.6kB  src/WorkspaceItem.tsx            
npm notice 206B   src/emptyChart.ts                
npm notice 14.2kB src/index.ts                     
npm notice 24B    src/lodash.d.ts                  
npm notice 35B    src/styled-components.d.ts       
npm notice 22B    src/uuid.d.ts                    
npm notice 2.6kB  style/HP_worflows.svg            
npm notice 1.0kB  style/index.css                  
npm notice 10.2kB style/logoLW_eric_outline2-01.svg
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/experiment-manager         
npm notice version:       1.0.0                                   
npm notice filename:      jupyter_vre-experiment-manager-1.0.0.tgz
npm notice package size:  27.3 kB                                 
npm notice unpacked size: 110.6 kB                                
npm notice shasum:        04789dba7d31c6b37c86084c75ed92c333b80353
npm notice integrity:     sha512-3NLO78Nkyw6Kk[...]YLvqSf+5JrNnw==
npm notice total files:   40                                      
npm notice 
jupyter_vre-experiment-manager-1.0.0.tgz

[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/vre-panel
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/vre-panel@1.0.0
npm notice === Tarball Contents === 
npm notice 331B   lib/AddCellDialog.d.ts         
npm notice 4.2kB  lib/AddCellDialog.js           
npm notice 1.5kB  lib/CellTracker.d.ts           
npm notice 15.6kB lib/CellTracker.js             
npm notice 63B    lib/Theme.d.ts                 
npm notice 452B   lib/Theme.js                   
npm notice 729B   lib/VREPanel.d.ts              
npm notice 5.3kB  lib/VREPanel.js                
npm notice 144B   lib/index.d.ts                 
npm notice 309B   lib/index.js                   
npm notice 249B   lib/widget.d.ts                
npm notice 2.9kB  lib/widget.js                  
npm notice 1.1kB  package.json                   
npm notice 2.3kB  src/AddCellDialog.tsx          
npm notice 17.8kB src/CellTracker.tsx            
npm notice 293B   src/Theme.ts                   
npm notice 3.6kB  src/VREPanel.tsx               
npm notice 20B    src/d3.d.ts                    
npm notice 176B   src/index.ts                   
npm notice 24B    src/lodash.d.ts                
npm notice 35B    src/styled-components.d.ts     
npm notice 79B    src/svg.d.ts                   
npm notice 1.3kB  src/widget.tsx                 
npm notice 2.8kB  style/icons/box-svgrepo-com.svg
npm notice 1.1kB  style/icons/icon_fairify.svg   
npm notice 11.6kB style/index.css                
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/vre-panel                  
npm notice version:       1.0.0                                   
npm notice filename:      jupyter_vre-vre-panel-1.0.0.tgz         
npm notice package size:  16.0 kB                                 
npm notice unpacked size: 74.0 kB                                 
npm notice shasum:        be6c12db613fa8f9e08daf1633b7af35b0d6bc88
npm notice integrity:     sha512-Y5h+Z/iWWugVG[...]xyJMSC4N4jewA==
npm notice total files:   26                                      
npm notice 
jupyter_vre-vre-panel-1.0.0.tgz

[LabBuildApp] > /usr/local/anaconda3/envs/jupyterlab/bin/npm pack /Users/diederik/Desktop/NaaVRE/packages/vre-menu
[LabBuildApp] npm notice 
npm notice 📦  @jupyter_vre/vre-menu@1.0.0
npm notice === Tarball Contents === 
npm notice 70B   lib/Theme.d.ts 
npm notice 463B  lib/Theme.js   
npm notice 145B  lib/index.d.ts 
npm notice 2.1kB lib/index.js   
npm notice 1.9kB package.json   
npm notice 300B  src/Theme.ts   
npm notice 2.1kB src/index.tsx  
npm notice 55B   style/index.css
npm notice === Tarball Details === 
npm notice name:          @jupyter_vre/vre-menu                   
npm notice version:       1.0.0                                   
npm notice filename:      jupyter_vre-vre-menu-1.0.0.tgz          
npm notice package size:  2.1 kB                                  
npm notice unpacked size: 7.2 kB                                  
npm notice shasum:        e144104d76f6320d8251305b4fd653aab40bc964
npm notice integrity:     sha512-bZWZODlRp3tr4[...]zZSlmEqwPNqoA==
npm notice total files:   8                                       
npm notice 
jupyter_vre-vre-menu-1.0.0.tgz

[LabBuildApp] > node /usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.94s.

[LabBuildApp] > node /usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
[LabBuildApp] yarn run v1.21.1
$ /usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.57s.

[LabBuildApp] > node /usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/staging/yarn.js run build:dev
[LabBuildApp] yarn run v1.21.1
$ npm run build

> @jupyterlab/application-top@3.6.1 build
> npm run clean && webpack


> @jupyterlab/application-top@3.6.1 clean
> rimraf build

[webpack-cli] /usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/cli.js:67
				/(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/gu,
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /(\p{Uppercase_Letter}+|\p{Lowercase_Letter}|\d)(\p{Uppercase_Letter}+)/: Invalid property name
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (/usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (/usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at get cli (/usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/index.js:120:10)
    at Function.cli (/usr/local/anaconda3/envs/jupyterlab/share/jupyter/lab/staging/node_modules/webpack/lib/util/memoize.js:22:13)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[LabBuildApp] JupyterLab failed to build
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/labapp.py", line 204, in start
    raise e

[LabBuildApp]   File "/usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/labapp.py", line 195, in start
    build(

[LabBuildApp]   File "/usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/commands.py", line 506, in build
    return handler.build(

[LabBuildApp]   File "/usr/local/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab/commands.py", line 722, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: JupyterLab failed to build

[LabBuildApp] Exiting application: JupyterLab
```

**Comment by DiederikBlanson** [comment]
Based on the error log above, it seems that there is an issue in Webpack, part of Jupyter Lab.

@skoulouzis What node version is running in your environment? `node --version` gives me 18.15.0
And based on your changes in the README, it seems that I do not have to run `npm install` in the root?

**Comment by DiederikBlanson** [comment]
@skoulouzis After switching from my Mac Intel to Mac M1, I am able to run it succesfully with this command `jupyter lab build && jupyter lab --debug --watch`. 

Do I have to perform the `make ...` commands everytime after a change? Because it seems that `jupyter lab build` does not pick up those changes?

And maybe this can be added to the README:
```
conda create -n jupyterlab  python=3.9 
conda activate jupyterlab 
```

**Comment by skoulouzis** [comment]
@DiederikBlanson Yes after ever assuming you have the  'jupyterlab' environment activated change you need to run the following:

```
make install-backend && make build-frontend && make install-ui && make link-ui 
```
and then 
```
jupyter lab build && jupyter lab --debug --watch
```

**Comment by DiederikBlanson** [comment]
@skoulouzis perfect! Then my local environment is working (aside from the vars that you have to send me). I check it by changing some UI components and those changes were reflected after the steps you described above.

I think we can close this ticket now? Although we might have to make a note that I was not able to run it on my Mac Intel, but for the M1 it worked
