### ISSUE TITLE
Build base docker throws errors 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#60]
Traceback (most recent call last):
File "/venv/lib/python3.10/site-packages/git/init.py", line 87, in <module>
refresh()
File "/venv/lib/python3.10/site-packages/git/init.py", line 76, in refresh
if not Git.refresh(path=path):
File "/venv/lib/python3.10/site-packages/git/cmd.py", line 340, in refresh
raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
- be included in your $PATH
- be set via $GIT_PYTHON_GIT_EXECUTABLE
- explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
- quiet|q|silence|s|none|n|0: for no warning or exception
- warn|w|warning|1: for a printed warning
- error|e|raise|r|2: for a raised exception

Example:
export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/venv/lib/python3.10/site-packages/tools/minio_tools.py", line 20, in <module>
from tools.helpers import objects_to_df
File "/venv/lib/python3.10/site-packages/tools/helpers.py", line 10, in <module>
import git
File "/venv/lib/python3.10/site-packages/git/init.py", line 89, in <module>
raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
- be included in your $PATH
- be set via $GIT_PYTHON_GIT_EXECUTABLE
- explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
- quiet|q|silence|s|none|n|0: for no warning or exception
- warn|w|warning|1: for a printed warning
- error|e|raise|r|2: for a raised exception

Example:
export GIT_PYTHON_REFRESH=quiet

**Comment by skoulouzis** [comment]
Apparently, this can be caused it your git client isn't to be found in $PATH. Could you verify that the binary git can be found?

I assume the git package for python makes some subprocess calls.
