### ISSUE TITLE
When we start jupyterlab from jupyterhub we get Missing required environment $JUPYTERHUB_SERVICE_URL

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#625]
Jupyterlab is not loading 
```python
    Traceback (most recent call last):
      File "/venv/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 274, in wrapped
        r = f(self, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib/python3.11/site-packages/jupyterhub/singleuser/extension.py", line 472, in load_config_file
        raise KeyError("Missing required environment $JUPYTERHUB_SERVICE_URL")
    KeyError: 'Missing required environment $JUPYTERHUB_SERVICE_URL'
```

**Comment by skoulouzis** [comment]
We may need to update helm:
```
helm repo update
helm upgrade --cleanup-on-fail vl-laserfarm jupyterhub/jupyterhub --version=2.0.0 --values vl-laserfarm.yaml -n vl-laserfarm
```
