### ISSUE TITLE
jupyterlab_vre/tests/test_handlers.py:148: AssertionError

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#673]
jupyterlab_vre/tests/test_handlers.py:148: AssertionError
----------------------------------------------------------------------------------- Captured stdout call -----------------------------------------------------------------------------------
test-retiling.json
<jupyterlab_vre.database.cell.Cell object at 0x7f842dc30390>
------------------------------------------------------------------------------------ Captured log call -------------------------------------------------------------------------------------
DEBUG    jupyterlab_vre.component_containerizer.handlers:handlers.py:217 Delete if exists: test-retiling-dev-skoulouzis
ERROR    tornado.application:web.py:1871 Uncaught exception POST /cellshandler (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:33901', method='POST', uri='/cellshandler', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/jupyterlab/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
    result = await result
             ^^^^^^^^^^^^
  File "/home/USER/workspace/NaaVRE/jupyterlab_vre/component_containerizer/handlers.py", line 253, in post
    kernel = payload['kernel']
             ~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
WARNING  tornado.application:handlers.py:612 Unhandled error
ERROR    tornado.access:web.py:2344 500 POST /cellshandler (127.0.0.1) 43.64ms

**Comment by skoulouzis** [comment]
It's no longer valid. Now all cells have a kernel key
