### ISSUE TITLE
Containerization fails when conf_* or its dependencies contains newlines

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE#831]
When containerizing the following cell, we get:

```python
conf_herwijnen = ['radar_volume_full_herwijnen',
                  1.0,
                  'https://api.dataplatform.knmi.nl/open-data/v1/datasets/radar_volume_full_herwijnen/versions/1.0/files',
                 'NL/HRW'] 
conf_denhelder = ['radar_volume_full_denhelder',
                 2.0,
                 'https://api.dataplatform.knmi.nl/open-data/v1/datasets/radar_volume_denhelder/versions/2.0/files',
                 'NL/DHL']
conf_radars = {'herwijnen' : conf_herwijnen,
              'denhelder' : conf_denhelder}
```

```python
# cell
print(conf_radars)
```

We get the error:

```
[E 2023-10-17 13:40:20.326 ServerApp] Uncaught exception POST /vl-vol2bird/user/berend/vre/containerizer/extract?1697550020136 (10.244.0.0)
    HTTPServerRequest(protocol='http', host='school.lifewatchdev.eu', method='POST', uri='/vl-vol2bird/user/berend/vre/containerizer/extract?1697550020136', version='HTTP/1.1', remote_ip='10.244.0.0')
    Traceback (most recent call last):
      File "/venv/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/venv/lib/python3.11/site-packages/jupyterlab_vre/component_containerizer/handlers.py", line 105, in post
        dependencies = extractor.infer_cell_dependencies(source, confs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib/python3.11/site-packages/jupyterlab_vre/services/extractor/extractor.py", line 83, in infer_cell_dependencies
        names.update(self.__extract_cell_names(confs[ck]))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib/python3.11/site-packages/jupyterlab_vre/services/extractor/extractor.py", line 102, in __extract_cell_names
        tree = ast.parse(cell_source)
               ^^^^^^^^^^^^^^^^^^^^^^
      File "/venv/lib/python3.11/ast.py", line 50, in parse
        return compile(source, filename, mode, flags,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<unknown>", line 1
        conf_radars = {'herwijnen' :  ['radar_volume_full_herwijnen',,
                                                                     ^
    SyntaxError: invalid syntax
[W 2023-10-17 13:40:20.327 ServerApp] Unhandled error
```

It looks like newlines get mangled when resolving `conf_` dependencies.

I suspect the error might come from https://github.com/QCDIS/NaaVRE/blob/451d84605dbca6750dbd78aeb14b2b0e1c1883fe/jupyterlab_vre/services/extractor/extractor.py#L134

**Comment by skoulouzis** [comment]
When running:

```python 
import ast

cell_source = "#Conf_bug\n\nconf_herwijnen = ['radar_volume_full_herwijnen',\n                  1.0,\n                  'https://api.dataplatform.knmi.nl/open-data/v1/datasets/radar_volume_full_herwijnen/versions/1.0/files',\n                 'NL/HRW'] \nconf_denhelder = ['radar_volume_full_denhelder',\n                 2.0,\n                 'https://api.dataplatform.knmi.nl/open-data/v1/datasets/radar_volume_denhelder/versions/2.0/files',\n                 'NL/DHL']\nconf_radars = {'herwijnen' : conf_herwijnen,\n              'denhelder' : conf_denhelder}"

tree = ast.parse(cell_source)
```

we get no error
