### ISSUE TITLE
Worklflow creation fails 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#85]
![Screenshot from 2022-03-27 11-22-47](https://user-images.githubusercontent.com/9680609/160275183-98420d8f-b9a5-4cfd-b760-a11504bf8197.png)
We get in logs: 

2022-03-27T09:20:15.226Z | Traceback (most recent call last):
2022-03-27T09:20:15.226Z | File "/opt/conda/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
2022-03-27T09:20:15.226Z | result = await result
2022-03-27T09:20:15.226Z | File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/handlers.py", line 402, in post
2022-03-27T09:20:15.226Z | parser = WorkflowParser(nodes, links)
2022-03-27T09:20:15.226Z | File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/workflows/parser.py", line 25, in __init__
2022-03-27T09:20:15.226Z | self.__parse_links()
2022-03-27T09:20:15.226Z | File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/workflows/parser.py", line 62, in __parse_links
2022-03-27T09:20:15.226Z | og_id_to = self.__get_og_node_id(link['to']['nodeId'])
2022-03-27T09:20:15.226Z | File "/opt/conda/lib/python3.9/site-packages/jupyterlab_vre/workflows/parser.py", line 73, in __get_og_node_id
2022-03-27T09:20:15.226Z | return self.nodes[node_id]['properties']['og_node_id']

**Comment by skoulouzis** [comment]
could not replicate
