### ISSUE TITLE
When we add the merger we get an error 

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/NaaVRE#90]
![Screenshot from 2022-03-31 18-09-43](https://user-images.githubusercontent.com/9680609/161100842-8aeed89c-7215-473b-b788-c3dcefe8c9f0.png)

When we add the merger we get an error: 

[E 2022-03-31 18:05:51.544 ServerApp] Uncaught exception POST /vre/workflow/export?1648742751531 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/vre/workflow/export?1648742751531', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_vre/handlers.py", line 403, in post
        parser = WorkflowParser(nodes, links)
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_vre/workflows/parser.py", line 32, in __init__
        self.__parse_links()
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_vre/workflows/parser.py", line 67, in __parse_links
        og_id_from = self.__get_og_node_id(link['from']['nodeId'])
      File "/home/alogo/anaconda3/envs/jupyterlab/lib/python3.9/site-packages/jupyterlab_vre/workflows/parser.py", line 77, in __get_og_node_id
        return self.nodes[node_id]['properties']['og_node_id']

**Comment by skoulouzis** [comment]
We need to implement the merger. This is set in #92

**Comment by skoulouzis** [comment]
#92 is closed
